/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/investors'
    | '/properties'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/properties'
    | '/admin/testimonials'
    | '/locations/$slug'
    | '/properties/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/investors'
    | '/properties'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/properties'
    | '/admin/testimonials'
    | '/locations/$slug'
    | '/properties/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/investors'
    | '/properties'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/properties'
    | '/admin/testimonials'
    | '/locations/$slug'
    | '/properties/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  InvestorsRoute: typeof InvestorsRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  InvestorsRoute: InvestorsRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LocationsSlugRoute: LocationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
