/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Admin_rootRouteImport } from './routes/admin/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as AdminPropertiesRouteImport } from './routes/admin/properties'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'

const Admin_rootRoute = Admin_rootRouteImport.update({
  id: '/admin/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof Admin_rootRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminIndexRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/__root': typeof Admin_rootRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/investors'
    | '/properties'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/leads'
    | '/admin/properties'
    | '/locations/$slug'
    | '/properties/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/investors'
    | '/properties'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/leads'
    | '/admin/properties'
    | '/locations/$slug'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/investors'
    | '/properties'
    | '/sitemap.xml'
    | '/admin/__root'
    | '/admin/leads'
    | '/admin/properties'
    | '/locations/$slug'
    | '/properties/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InvestorsRoute: typeof InvestorsRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Admin_rootRoute: typeof Admin_rootRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/__root': {
      id: '/admin/__root'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InvestorsRoute: InvestorsRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Admin_rootRoute: Admin_rootRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
